// Embeds assets/NotoNaskhArabic-Regular.ttf as base64 in src/font.ts.
// Run: node scripts/embed-font.mjs
import { readFileSync, writeFileSync } from "node:fs";

const b64 = readFileSync(new URL("../assets/NotoNaskhArabic-Regular.ttf", import.meta.url)).toString("base64");
writeFileSync(
  new URL("../src/font.ts", import.meta.url),
  `// Generated by scripts/embed-font.mjs — do not edit.\nexport const NOTO_NASKH_ARABIC_B64 =\n  "${b64}";\n`
);
console.log(`Embedded font: ${b64.length} base64 chars`);
